// src/pages/Parents/UtilityLists/components/UtilityListPDF.jsx
import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 50,
    fontSize: 10,
    fontFamily: "Helvetica",
    backgroundColor: "#FFFFFF",
  },
  header: {
    borderBottomWidth: 2,
    borderBottomColor: "#10b981", // Emerald 500
    paddingBottom: 15,
    marginBottom: 25,
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#064e3b", // Emerald 900
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  subtitle: {
    fontSize: 10,
    color: "#6b7280",
    marginTop: 6,
    fontWeight: "medium",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f0fdf4", // Emerald 50
    padding: 8,
    borderRadius: 4,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#d1fae5",
  },
  headerLabel: {
    fontSize: 9,
    fontWeight: "bold",
    color: "#047857",
    textTransform: "uppercase",
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  index: {
    width: "8%",
    color: "#10b981",
    fontWeight: "bold",
  },
  itemText: {
    width: "72%",
    color: "#1f2937",
    fontSize: 11,
  },
  quantity: {
    width: "20%",
    textAlign: "right",
    color: "#065f46",
    fontSize: 10,
    fontWeight: "bold",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 50,
    right: 50,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 10,
    textAlign: "center",
    fontSize: 8,
    color: "#9ca3af",
  },
});

// Utility to capitalize only the first letter
const capitalizeFirst = (str) => {
  if (!str) return "";
  return str.charAt(0).toUpperCase() + str.slice(1);
};

export default function UtilityListPDF({ list, items }) {
  const today = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>{list.title}</Text>
          <Text style={styles.subtitle}>
            BindFam • Completed Items Summary Report
          </Text>
        </View>

        {/* Column Headers */}
        <View style={styles.tableHeader}>
          <Text style={[styles.headerLabel, { width: "8%" }]}>#</Text>
          <Text style={[styles.headerLabel, { width: "72%" }]}>Item Description</Text>
          <Text style={[styles.headerLabel, { width: "20%", textAlign: "right" }]}>Qty</Text>
        </View>

        {/* Items List */}
        {items.map((item, idx) => (
          <View key={item.id || idx} style={styles.itemRow}>
            <Text style={styles.index}>{idx + 1}</Text>
            <Text style={styles.itemText}>
              {capitalizeFirst(item.title)}
            </Text>
            <Text style={styles.quantity}>
              {item.quantity ? item.quantity : "-"}
            </Text>
          </View>
        ))}

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text>
            This is an automated report generated by BindFam Utility Lists.
          </Text>
          <Text style={{ marginTop: 4 }}>
            Report Date: {today}
          </Text>
        </View>
      </Page>
    </Document>
  );
}